### ISSUE TITLE
List inside of details is automatically collapsed

### ISSUE THREAD

**Issue by simonwammerfors** [Mamaduka/toggles#10] opened 2022-12-14 13:33 UTC
In the editor, if I put a list block inside the details element and then try to edit the list, the details section is automatically collapsed.

The only way to edit that list is to select the toggles block and select "Open by default", edit the list and then deselect "Open by default" again.

**Comment by danbitzer** [comment] 2023-02-17 02:33
I'm also facing this issue. 

I'm guessing it's caused by list items being child blocks of a list block and the toggle collapses when a direct child of the toggle content doesn't have focus.

**Comment by motla** [comment] 2023-06-17 09:26
Thanks @Mamaduka for your work on this plugin. It's simple, lightweight and effective.

However I'm also facing this issue 🙂 

Seems that Google Chrome doesn't like it and crashes the page with an error when we focus a child block which is a list or a button:

![image](https://github.com/Mamaduka/toggles/assets/16179413/6b8224b2-f90d-4e86-837a-2c7081191c0e)

Maybe the workaround is to always display the toggles open in the Gutenberg Editor...

**Comment by Mamaduka** [comment] 2023-06-17 11:58
Thanks for the comment, @motla!

Crashing the browser tabs isn't good. I might have a solution for this and will try to release a fix shortly.

**Comment by Mamaduka** [comment] 2023-06-17 14:05
The issue should be fixed in v1.1.0. I just released it a few minutes ago.

**Closed as completed by Mamaduka** 2023-06-17 14:05 UTC

**Comment by motla** [comment] 2023-06-17 14:07
Tested, perfect. Thank you!
